# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2359dbba4d749a2311824a67f0183486ab1be7b932ccbf2773918a03e2f7a547c390d7455dc982ee7021daa1898a30715721f3bc7056fb647e9f034abdefd2c

test:
  secret_key_base: afd7c7d46f1c1812634788beacbb4a09bb648f8c9859679013e189e1ba3ac37351b227e7540d9a16450e8b1515f382435b6a2429634deb1a7e7ade76d61d7438

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
